<?php

/**
 * @file
 * Contains customisations for the webform module.
 */

\Drupal::moduleHandler()->loadInclude('webform', 'inc', 'includes/webform.theme.template');

/**
 * Implements hook_theme().
 */
function bhcc_webform_date_theme() {
  return [
    'bhcc_webform_date' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Prepares variables for BHCC Webform templates.
 *
 * Default template: bhcc_webform_date.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 */
function template_preprocess_bhcc_webform_date(array &$variables) {
  // Here you can get the composite element and alter it.
  _template_preprocess_webform_composite($variables);
}

/**
 * Implements hook_preprocess_datetime_form().
 */
function bhcc_webform_date_preprocess_datetime_form(array &$variables) {

  $extended_bhcc_webform_elements = [
    'bhcc_webform_date_of_birth',
    'bhcc_webform_date',
  ];

  $type = $variables['element']['#type'];

  if (in_array($type, $extended_bhcc_webform_elements)) {
    $variables['attributes']['class'][] = 'localgov-forms-date bhcc-localgov-date';
  }

}
